spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      locator:
        enabled: true
    kubernetes:
      loadbalancer:
        enabled: true
      enabled: true

eureka:
  client:
    enabled: false


security:
  authURL: https://sandbox.avicss.com
  key: securityKey
