# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
 
spring:
  application:
    name: shoppingcart-service
  data:
    mongodb:
      uri: mongodb+srv://sandbox-user:oWU49YArvOS1W3QA@cluster0-zegr3.mongodb.net/shoppingcart?retryWrites=trues

  cloud:
    stream:
      bindings:
        output:
          destination: checkout

    gcp:
      sql:
        enable: false
      project-id: spheric-duality-248208
      credentials:
        location: classpath:service_account_sandbox.json

server:
  port: 8080


swagger:
  enable: true

firebase:
  config:
    path: firebase-sandbox.json


pricing:
  minimumCharge: 15
  deliveryFees: 5

logging:
  level:
    root: ERROR