spring:
  application:
    name: user-service
  data:
    mongodb:
      database: user
      host: cluster0.0gjsx.mongodb.net
      username: sandbox-user
      password: JL9hCbGkaJIWZXdz
      


server:
  port: 8081

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: INFO
    org.mongodb.driver.cluster: ERROR
    org.mongodb.driver.connection: ERROR
    org.zalando.logbook: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

logbook:
  include:
    - /user/**
  filter.enabled: true
  secure-filter.enabled: true
  logbook.format.style: JSON

integration:
  hubspot: true
  qob: false
  commerce: false
  offlineEmail: false