spring:
  application:
    name: aircraft-service
  data:
    mongodb:
      database: aircraft

server:
 port: 8098

logging:
 pattern:
   file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
   console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
 level:
   root: INFO
   org.mongodb.driver.cluster: ERROR
   org.mongodb.driver.connection: ERROR
   org.zalando.logbook: TRACE
   org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

logbook:
 include:
   - /aircraft/**
 filter.enabled: true
 secure-filter.enabled: true
 logbook.format.style: JSON

info:
  app:
    name: Aircraft API
    description: This is aircraft API
    version: 1.0.0