spring:
  application:
    name: api-gateway

  
server:
 port: 8080

logging:
 pattern:
   file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
   console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
 level:
   root: INFO
   org.mongodb.driver.cluster: ERROR
   org.mongodb.driver.connection: ERROR
   org.zalando.logbook: TRACE
   org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

logbook:
 include:
   - /api-gateway/**
 filter.enabled: true
 secure-filter.enabled: true
 logbook.format.style: JSON

app:
  security:
    jwt:
      private-key-passphrase: password
      key-alias: jwtsigning
      keystore-password: password
      keystore-location: keys/keystore.jks

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/

zuul:
    ignored-services: '*'
    routes:
        auth-service:
            path: /auth/**
            sensitive-headers: 'Cookie,Set-Cookie '
            service-id: AUTH-SERVICE
            strip-prefix: false
        gallery-service:
            path: /gallery/**
            service-id: gallery-service
