spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      locator:
        enabled: false
    kubernetes:
      loadbalancer:
        enabled: false
      enabled: false

security:
  authURL: https://sandbox.avicss.com
  key: securityKey