spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      locator:
        enabled: false
    kubernetes:
      loadbalancer:
        enabled: false
      enabled: false

