spring:
  application:
    name: flight-search-service
  data:
    mongodb:
      database: flight

server:
 port: 8080

logging:
 pattern:
   file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
   console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
 level:
   root: INFO
   org.mongodb.driver.cluster: ERROR
   org.mongodb.driver.connection: ERROR
   org.zalando.logbook: TRACE
   org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

logbook:
 include:
   - /flight-search/**
 filter.enabled: true
 secure-filter.enabled: true
 logbook.format.style: JSON

info:
  app:
    name: Flight search API
    description: This is flight search API
    version: 1.0.0