spring:
  application:
    name: terminal-service
  data:
    mongodb:
      database: terminal

server:
 port: 8090

logging:
 pattern:
   file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
   console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
 level:
   root: INFO
   org.mongodb.driver.cluster: ERROR
   org.mongodb.driver.connection: ERROR
   org.zalando.logbook: TRACE
   org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

logbook:
 include:
   - /terminal/**
 filter.enabled: true
 secure-filter.enabled: true
 logbook.format.style: JSON

info:
  app:
    name: Terminal API
    description: This is terminal API
    version: 1.0.0