spring:
  application:
    name: user-service
  data:
    mongodb:
      database: user

server:
  port: 8082

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: INFO
    org.mongodb.driver.cluster: ERROR
    org.mongodb.driver.connection: ERROR
    org.zalando.logbook: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

email:
  reset: https://www.avicss.com/
  enable: true

logbook:
  include:
    - /user/**
  filter.enabled: true
  secure-filter.enabled: true
  logbook.format.style: JSON


info:
  app:
    name: User API
    description: This is user API
    version: 1.0.0