eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    use-dns-for-fetching-service-urls: true
  instance:
    hostname: localhost